"""add geos referential tables

Revision ID: c3f9a1d47b2e
Revises: 7b1a4c8e2f90
Create Date: 2026-10-04 21:41:56.712451

The 14 GEOS entities were added to the ORM in commit 0b389ae (2026-08-17,
"GEOS — 14 entités + moteur SNN unifié") without ever being added to the
Alembic history: congo_brain/models/__init__.py did not import
congo_brain.models.geos.entities, so alembic/env.py's target_metadata never
saw them and `--autogenerate` could not detect them either.

A deployed database therefore had no geos_* table at all: the app booted,
the health check stayed green, and the first query on the RDC referential
failed with "relation does not exist". Local dev and the test suite never
saw it because congo_brain.core.database.init_db() and tests/conftest.py both
build the schema from Base.metadata.create_all, never through Alembic.

This revision is purely additive: it creates the 14 missing tables in foreign
key dependency order (ministries/provinces first, contracts/payments last)
and touches no existing table.
"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c3f9a1d47b2e'
down_revision: Union[str, Sequence[str], None] = '7b1a4c8e2f90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geos_ministries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('budget_allocated', sa.Float(), nullable=True),
    sa.Column('budget_executed', sa.Float(), nullable=True),
    sa.Column('optimization_score', sa.Float(), nullable=True),
    sa.Column('transparency_score', sa.Float(), nullable=True),
    sa.Column('performance_score', sa.Float(), nullable=True),
    sa.Column('satisfaction_score', sa.Float(), nullable=True),
    sa.Column('employees_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_geos_ministries_id'), 'geos_ministries', ['id'], unique=False)
    op.create_table('geos_provinces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('population', sa.Float(), nullable=True),
    sa.Column('area_km2', sa.Float(), nullable=True),
    sa.Column('gdp', sa.Float(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('poverty_rate', sa.Float(), nullable=True),
    sa.Column('literacy_rate', sa.Float(), nullable=True),
    sa.Column('electricity_access', sa.Float(), nullable=True),
    sa.Column('water_access', sa.Float(), nullable=True),
    sa.Column('internet_access', sa.Float(), nullable=True),
    sa.Column('security_index', sa.Float(), nullable=True),
    sa.Column('governance_score', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_geos_provinces_id'), 'geos_provinces', ['id'], unique=False)
    op.create_table('geos_taxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tax_type', sa.String(length=50), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('base', sa.Float(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('compliance_rate', sa.Float(), nullable=True),
    sa.Column('evasion_estimate', sa.Float(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geos_taxes_id'), 'geos_taxes', ['id'], unique=False)
    op.create_table('geos_budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ministry_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('allocated', sa.Float(), nullable=True),
    sa.Column('executed', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ministry_id'], ['geos_ministries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geos_budgets_id'), 'geos_budgets', ['id'], unique=False)
    op.create_table('geos_citizens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('income_monthly', sa.Float(), nullable=True),
    sa.Column('education_level', sa.String(length=50), nullable=True),
    sa.Column('employment_status', sa.String(length=50), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('has_electricity', sa.Boolean(), nullable=True),
    sa.Column('has_water', sa.Boolean(), nullable=True),
    sa.Column('has_internet', sa.Boolean(), nullable=True),
    sa.Column('satisfaction_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['province_id'], ['geos_provinces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geos_citizens_id'), 'geos_citizens', ['id'], unique=False)
    op.create_table('geos_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('employees', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('production_cost', sa.Float(), nullable=True),
    sa.Column('tax_burden', sa.Float(), nullable=True),
    sa.Column('admin_cost', sa.Float(), nullable=True),
    sa.Column('corruption_cost', sa.Float(), nullable=True),
    sa.Column('logistics_cost', sa.Float(), nullable=True),
    sa.Column('energy_cost', sa.Float(), nullable=True),
    sa.Column('is_formal', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['province_id'], ['geos_provinces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geos_companies_id'), 'geos_companies', ['id'], unique=False)
    op.create_table('geos_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('target', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('province_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['province_id'], ['geos_provinces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geos_indicators_id'), 'geos_indicators', ['id'], unique=False)
    op.create_table('geos_infrastructures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('infra_type', sa.String(length=50), nullable=True),
    sa.Column('length_km', sa.Float(), nullable=True),
    sa.Column('capacity', sa.Float(), nullable=True),
    sa.Column('condition_score', sa.Float(), nullable=True),
    sa.Column('annual_maintenance_cost', sa.Float(), nullable=True),
    sa.Column('users_served', sa.Integer(), nullable=True),
    sa.Column('is_functional', sa.Boolean(), nullable=True),
    sa.Column('construction_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['province_id'], ['geos_provinces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geos_infrastructures_id'), 'geos_infrastructures', ['id'], unique=False)
    op.create_table('geos_markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('province_id', sa.Integer(), nullable=True),
    sa.Column('total_revenue', sa.Float(), nullable=True),
    sa.Column('total_employment', sa.Integer(), nullable=True),
    sa.Column('avg_price_index', sa.Float(), nullable=True),
    sa.Column('competition_index', sa.Float(), nullable=True),
    sa.Column('informal_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['province_id'], ['geos_provinces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geos_markets_id'), 'geos_markets', ['id'], unique=False)
    op.create_table('geos_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('ministry_id', sa.Integer(), nullable=True),
    sa.Column('province_id', sa.Integer(), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('budget_allocated', sa.Float(), nullable=True),
    sa.Column('budget_executed', sa.Float(), nullable=True),
    sa.Column('cs_impact', sa.Float(), nullable=True),
    sa.Column('ps_impact', sa.Float(), nullable=True),
    sa.Column('gr_impact', sa.Float(), nullable=True),
    sa.Column('nrv_impact', sa.Float(), nullable=True),
    sa.Column('dwl_impact', sa.Float(), nullable=True),
    sa.Column('ec_impact', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('jobs_created', sa.Integer(), nullable=True),
    sa.Column('corruption_risk', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ministry_id'], ['geos_ministries.id'], ),
    sa.ForeignKeyConstraint(['province_id'], ['geos_provinces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geos_projects_id'), 'geos_projects', ['id'], unique=False)
    op.create_table('geos_public_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=True),
    sa.Column('willingness_to_pay', sa.Float(), nullable=True),
    sa.Column('actual_price', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('access_time_hours', sa.Float(), nullable=True),
    sa.Column('indirect_cost', sa.Float(), nullable=True),
    sa.Column('coverage_pct', sa.Float(), nullable=True),
    sa.Column('satisfaction_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['province_id'], ['geos_provinces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geos_public_services_id'), 'geos_public_services', ['id'], unique=False)
    op.create_table('geos_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=True),
    sa.Column('mineral_type', sa.String(length=50), nullable=True),
    sa.Column('reserves_tons', sa.Float(), nullable=True),
    sa.Column('annual_production_tons', sa.Float(), nullable=True),
    sa.Column('market_value_per_ton', sa.Float(), nullable=True),
    sa.Column('local_processing_pct', sa.Float(), nullable=True),
    sa.Column('tax_rate', sa.Float(), nullable=True),
    sa.Column('employees', sa.Integer(), nullable=True),
    sa.Column('export_value', sa.Float(), nullable=True),
    sa.Column('environmental_cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['province_id'], ['geos_provinces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geos_resources_id'), 'geos_resources', ['id'], unique=False)
    op.create_table('geos_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('awarded_value', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('award_date', sa.DateTime(), nullable=True),
    sa.Column('is_competitive', sa.Boolean(), nullable=True),
    sa.Column('has_beneficial_ownership', sa.Boolean(), nullable=True),
    sa.Column('corruption_flag', sa.Boolean(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['geos_companies.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['geos_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geos_contracts_id'), 'geos_contracts', ['id'], unique=False)
    op.create_table('geos_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('beneficiary', sa.String(length=200), nullable=True),
    sa.Column('purpose', sa.String(length=200), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('anomaly_flag', sa.Boolean(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['geos_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geos_payments_id'), 'geos_payments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_geos_payments_id'), table_name='geos_payments')
    op.drop_table('geos_payments')
    op.drop_index(op.f('ix_geos_contracts_id'), table_name='geos_contracts')
    op.drop_table('geos_contracts')
    op.drop_index(op.f('ix_geos_resources_id'), table_name='geos_resources')
    op.drop_table('geos_resources')
    op.drop_index(op.f('ix_geos_public_services_id'), table_name='geos_public_services')
    op.drop_table('geos_public_services')
    op.drop_index(op.f('ix_geos_projects_id'), table_name='geos_projects')
    op.drop_table('geos_projects')
    op.drop_index(op.f('ix_geos_markets_id'), table_name='geos_markets')
    op.drop_table('geos_markets')
    op.drop_index(op.f('ix_geos_infrastructures_id'), table_name='geos_infrastructures')
    op.drop_table('geos_infrastructures')
    op.drop_index(op.f('ix_geos_indicators_id'), table_name='geos_indicators')
    op.drop_table('geos_indicators')
    op.drop_index(op.f('ix_geos_companies_id'), table_name='geos_companies')
    op.drop_table('geos_companies')
    op.drop_index(op.f('ix_geos_citizens_id'), table_name='geos_citizens')
    op.drop_table('geos_citizens')
    op.drop_index(op.f('ix_geos_budgets_id'), table_name='geos_budgets')
    op.drop_table('geos_budgets')
    op.drop_index(op.f('ix_geos_taxes_id'), table_name='geos_taxes')
    op.drop_table('geos_taxes')
    op.drop_index(op.f('ix_geos_provinces_id'), table_name='geos_provinces')
    op.drop_table('geos_provinces')
    op.drop_index(op.f('ix_geos_ministries_id'), table_name='geos_ministries')
    op.drop_table('geos_ministries')
    # ### end Alembic commands ###
