apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    {{- include "congo-brain.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key: {{ .Values.env.SECRET_KEY | b64enc | quote }}
